### ISSUE TITLE
Simulation isn't running in WISDEM if I change the material properties in geometry yaml file.

### ISSUE THREAD

**Issue by Al-Evan** [WISDEM/WISDEM#423] opened 2023-03-14 18:48 UTC
if I change the material properties of UD and/or Biax and/or Triax and/or Resin according to my project requirement in geometry yaml file (Example 02_reference turbine IEA 3p4 RWT) it doesn't run and gives me suggestion for changing the fiber volume fraction (fvf) and fiber weight fraction (fwf) which I don't want to change as I want to keep then similar to the baseline blade as I want to compare the results of baseline and redesigned blade. Can you suggest me how can I fix this issue?
 
 Any suggestions will be greatly appreciated.

Produce the error by running the following files in wisdem:
1. IEA-3p4-130-RWT_calculated.yaml (Geometry yaml)
2. modeling_options.yaml (modeling yaml)
3. analysis_options_calculated.yaml (analysis yaml)

Simulation runs with the baseline condition with the following yaml file:
1. IEA-3p4-130-RWT.yaml (Geometry yaml)
2. modeling_options.yaml (modeling yaml)
3. analysis_options.yaml (analysis yaml)
[analysis_options.txt](https://github.com/WISDEM/WISDEM/files/10972659/analysis_options.txt)
[analysis_options_calculated.txt](https://github.com/WISDEM/WISDEM/files/10972660/analysis_options_calculated.txt)
[IEA-3p4-130-RWT.txt](https://github.com/WISDEM/WISDEM/files/10972661/IEA-3p4-130-RWT.txt)
[IEA-3p4-130-RWT_calculated.txt](https://github.com/WISDEM/WISDEM/files/10972662/IEA-3p4-130-RWT_calculated.txt)
[modeling_options.txt](https://github.com/WISDEM/WISDEM/files/10972663/modeling_options.txt)

**Comment by ptrbortolotti** [comment] 2023-03-14 19:49
Hello,
you're seeing the error because you're changing the laminate density without adjusting ply thickness, fvf, and fwf. Your new laminate has inconsistent properties and WISDEM stops. You can comment out the checks here https://github.com/WISDEM/WISDEM/blob/c07ce084b582322fa2e73da70ce2396abecf6e7d/wisdem/glue_code/gc_WT_DataStruc.py#L2899 if you fee like, but watch out because the blade cost estimate will be impacted. I'll add the it's only about the density, you can change E and G props freely.
I hope this helps.
Regards,
Pietro

**Comment by Al-Evan** [comment] 2023-03-14 19:59
Thank you for your prompt response.
From where I can adjust the ply thickness and have make the laminate properties consistent? (I want to have a cost estimate later as well. So any suggestions for this?)

And also the last line from your reply- "I'll add the it's only about the density, you can change E and G props freely." are you suggesting that commenting out line 2899 I can use E and G prop value freely?

**Comment by ptrbortolotti** [comment] 2023-03-14 20:14
The error should only be caused by the change in density.
You can adjust fiber volume fraction using this formula 
https://github.com/WISDEM/WISDEM/blob/c07ce084b582322fa2e73da70ce2396abecf6e7d/wisdem/glue_code/gc_WT_DataStruc.py#L2896
Fiber weight fraction with this formula
https://github.com/WISDEM/WISDEM/blob/c07ce084b582322fa2e73da70ce2396abecf6e7d/wisdem/glue_code/gc_WT_DataStruc.py#L2914
And ply thickness with this formula
https://github.com/WISDEM/WISDEM/blob/c07ce084b582322fa2e73da70ce2396abecf6e7d/wisdem/glue_code/gc_WT_DataStruc.py#L2936

**Comment by Al-Evan** [comment] 2023-03-14 20:30
Thank you. I will get back to you if/ when I will face any further complications.

**Comment by ptrbortolotti** [comment] 2023-04-06 03:02
I will close this for now

**Closed by ptrbortolotti** 2023-04-06 03:02 UTC
