### ISSUE TITLE
DLL load failed while importing _precomp

### ISSUE THREAD

**Issue by BerendvanHove** [WISDEM/WISDEM#505] opened 2024-03-27 09:54 UTC
Hi everyone, I've installed WISDEM in an anaconda environment correctly (at least I think so), but when I try to run it I have the following error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Anaconda\envs\wisdem\Scripts\wisdem.exe\__main__.py", line 4, in <module>
  File "C:\Anaconda\envs\wisdem\Lib\site-packages\wisdem\__init__.py", line 1, in <module>
    from wisdem.glue_code.runWISDEM import run_wisdem
  File "C:\Anaconda\envs\wisdem\Lib\site-packages\wisdem\glue_code\runWISDEM.py", line 11, in <module>
    from wisdem.glue_code.glue_code import WindPark
  File "C:\Anaconda\envs\wisdem\Lib\site-packages\wisdem\glue_code\glue_code.py", line 4, in <module>
    from wisdem.rotorse.rotor import RotorSE
  File "C:\Anaconda\envs\wisdem\Lib\site-packages\wisdem\rotorse\rotor.py", line 7, in <module>
    from wisdem.rotorse.rotor_elasticity import RotorElasticity
  File "C:\Anaconda\envs\wisdem\Lib\site-packages\wisdem\rotorse\rotor_elasticity.py", line 7, in <module>
    from wisdem.rotorse.precomp import PreComp, Profile, CompositeSection, Orthotropic2DMaterial
  File "C:\Anaconda\envs\wisdem\Lib\site-packages\wisdem\rotorse\precomp.py", line 21, in <module>
    from wisdem.rotorse._precomp import precomp as _precomp
ImportError: DLL load failed while importing _precomp: cannot find correct module

When I look in that folder, there is definitely a file named precomp.py, so I do not understand why it isn't able to use the file. I hope someone can help me, thanks in advance.

**Comment by gbarter** [comment] 2024-03-28 02:20
Hi- Thanks for your interest in WISDEM.  This seems to be a [recent issue](https://github.com/WISDEM/CCBlade/issues/32).  Unfortunately, we have not been able to replicate the issue on our side or get to the root cause.

My best suggestion for now is to do `conda install wisdem` and see if that works for your purposes.

**Comment by BerendvanHove** [comment] 2024-03-29 12:54
Hi, thanks for your response. I started fresh with a new environment and tried **conda install wisdem** upon your suggestion. First it said:

Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - wisdem

Current channels:

  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.)

I looked on the provided website and then used: **conda install conda-forge::wisdem**, after which installed. When I then try to run WISDEM it gives the following error: **Fatal error in launcher: Unable to create process using '"D:\bld\wisdem_1711495830381\_h_env\python.exe"**

Can you help me with this problem?

**Comment by gbarter** [comment] 2024-03-29 13:03
That last error looks similar to #506 .  Are you running WISDEM with `wisdem geometry.yaml modeling.yaml analysis.yaml`?  Have you tried running by calling python directly?  Perhaps `python WISDEM/examples/02_reference_turbines/iea3p4_driver.py` ?

**Comment by gbarter** [comment] 2024-04-25 16:58
I have ported the offending fortran library to python to try to address this issue.  If you are comfortable doing so, could you try out the new `pyprecomp` branch with `git checkout pyprecomp` (likely have to do `git pull` first) and let me know if that resolves the barrier for you?

**Comment by gbarter** [comment] 2024-04-29 16:40
Both the Fortran compilation issue and the availability of the `wisdem` and `compare_designs` commands in the conda package should be fixed by tomorrow in the recent v3.15 release.

**Closed by gbarter** 2024-04-29 16:40 UTC
